#+TITLE: Natural Born Cyborgs: An Eternal Golden Braid\newline(Working Title)
#+AUTHOR: Luís Arandas et al.
#+OPTIONS: H:3 num:t toc:nil ':t
#+LATEX_HEADER: \usepackage[a4paper,bindingoffset=0.2in,left=1in,right=1in,top=1in,bottom=1in,footskip=.25in]{geometry}
#+LATEX_HEADER: \usepackage[dvipsnames]{xcolor}
#+LATEX_HEADER: \usepackage{fontspec}
#+LATEX_HEADER: \usepackage[math-style=french]{unicode-math}
#+LATEX_HEADER: \usepackage{mathtools}
#+LATEX_HEADER: \setmathfont[math-style=upright]{DejaVu Sans Mono}
#+LATEX_HEADER: \setmonofont[scale=.8,Color=blue]{Ubuntu Mono}
#+LATEX_HEADER: \newfontfamily{\mm}[scale=.8,Color=red]{DejaVu Sans Mono}
#+LATEX_HEADER: \setmainfont[BoldFont=EB Garamond,BoldFeatures={Color=ff0000}]{EB Garamond}
#+LATEX_HEADER: \newcommand{\hookuparrow}{\mathrel{\rotatebox[origin=c]{90}{$\hookrightarrow$}}}
#+LATEX_HEADER: \usepackage{fix-abstract}
#+LATEX_HEADER: \definecolor{pale}{HTML}{fffff8}
#+LATEX_HEADER: \definecolor{orgone}{HTML}{83a598}
#+LATEX_HEADER: \definecolor{orgtwo}{HTML}{fabd2f}
#+LATEX_HEADER: \definecolor{orgthree}{HTML}{d3869b}
#+LATEX_HEADER: \definecolor{orgfour}{HTML}{fb4933}
#+LATEX_HEADER: \definecolor{orgfive}{HTML}{b8bb26}
#+LATEX_HEADER: \definecolor{gruvbg}{HTML}{1d2021}
#+LATEX_HEADER: \newenvironment*{emptyenv}{}{}
#+LATEX_HEADER: \usepackage{sectsty}
#+LATEX_HEADER: \sectionfont{\normalfont\color{red}\selectfont}        
#+LATEX_HEADER: \subsectionfont{\normalfont\selectfont}     
# #+LATEX_HEADER: \subsubsectionfont{\normalfont\selectfont}
#+LATEX_HEADER: \paragraphfont{\normalfont\selectfont}
#+LATEX_HEADER: \subsubsectionfont{\normalfont\selectfont\color{black!50}}
**
#+BEGIN_LATEX
\begin{abstract}
\noindent
The aim of this paper to re-imagine “Human Computer Interaction” as a
co-evolutionary process.  We address this through a detailed
reconsideration of the concepts “creativity” and “ethics”.  The
motivation for the investigation is that ethics also hard for humans
to get right — e.g., consider ongoing concerns about climate change,
genocides, etc. — so, accordingly, it becomes relevant to consider
computational ethics not just in terms abstractions like trolley
problems, but within a concrete historical context.  Similarly, we are
led to look at “creativity” not in terms of an auteur — or even
necessarily a single agent, but in terms of systems interaction.  By
bringing together philosophical and computing literature, we hope to
develop a set of salient ethical guidelines for researchers and
practitioners in computing fields.
\end{abstract}
#+END_LATEX
** \setcounter{tocdepth}{1}
\tableofcontents
# IMPORT
* Introduction
** The Introduction will have to do some heavy lifting to explain that we're talking about "creativity" in a way that's not entirely familiar. I want to re-imagine "Human Computer Interaction" as a co-evolutionary process that has been developing over long time spans. There's nothing too shocking about that, but it can be hard to express in words. To make the paper accessible to reviewers we need to be careful how we present our concepts of "creativity" and "ethics". The basic motivation is that ethics is pretty hard for humans to get right (e.g., consider climate change, genocides, etc.), so we need to think about computational ethics not just in terms of trolley problems, but in a broader context. Similarly, we want to look at “creativity” not just in terms of an auteur — or even necessarily a single agent!
** [[*Premises][Premises]] — /‘Human-computer interaction’ is a bigger deal than we might think at first glance!.../
** [[*Scope][Scope]]— TOCHI — /covers humans interacting with computers/
:PROPERTIES:
:later: 1607173640608
:done: 1607173639362
:END:
*** Our RQ: WHAT ARE SUITABLE ETHICS FOR HCI+HCCC DESIGNERS?
** [[*Approach][Approach]] — /We will survey philosophy and its applications in CS; then, we will describe possible next steps for research./
* Approach
:PROPERTIES:
  :tag: HL
  :END:

** Main idea survey philosophical ideas that are relevant and look at how they are used in practice.
- We want to look at what is HCCC, how does it work overall, how this influence scientists in the practice
** An inspiring model: “Peer Production: A Form of Collective Intelligence” (Benkler et al.)
#+begin_quote
In the rest of this chapter, we describe the development of the
academic literature on peer production and collective intelligence in
three areas – organization, motivation, and quality. In each area, we
introduce foundational work consisting primarily of earlier
scholarship that sought to describe peer production and establish its
legitimacy. Subsequently, we characterize work, usually more recent,
that seeks to pursue new directions and to derive more nuanced
analytical insights. — https://mako.cc/benkler_shaw_hill-peer_production_ci.pdf
#+end_quote
* Index of Ethics Paper
:PROPERTIES:
  :tag: HL
  :END:

** [[*Introduction][Introduction]] — Ethics of HCCC
*** [[*Background][Background]] — /Bring people up to speed with what we need to think about “HCCC” the broad way we talk about it./
** Philosophy and Ethics — Intersected with Computer Science Practice
*** [[*Survey introduction][Survey introduction]]
*** Western philosophy and ethics definition (as basic for the paper) [[*1.0][1.0]]
*** Relating western to nonwestern practices [[*2.0][2.0]]
*** Phenomenology and being [[*3.0][3.0]]
*** Embodied cognition, social intelligence, collective intelligence [[*4.0][4.0]]
*** Reprise: Evolution regarding all of these [[*5.0][5.0]]
** [[*Case studies][Case studies]] — if wanted
** [[*Discussion][Discussion]] How can we build on the survey above to plan new directions of work?
* Background
:PROPERTIES:
  :tag: HL
  :END:

** [[*Background: Concepts][Background: Concepts]]
** [[*Background: HCCC][Background: HCCC]]
** [[*Background: Other][Background: Other]]
(For miscellaneous stuff.)
* Background: Concepts
:PROPERTIES:
  :tag: HL
  :END:

#+begin_quote
At this point our aim is to set up the framework for reviewers to
evaluate the paper’s contributions, not to dazzle them with esoteric
concepts!  Nevertheless some framing concepts can be helpful.
#+end_quote

** Philosophy:
- “Creative evolution” from Bergson
- “Anthropotechnics” from Sloterdijk.
** Anthropology:
- “Chaîne opératoire” from André Leroi-Gourhan et al.
- Histories of the evolution of intelligence (sociality & tools being key focal points)
** Computing
- “Computational Social Creativity” is one sub-field of computing research that is apropos, because it considers creativity spread across a social field.
** Other fields:
- “Professional ethics” (e.g., with reference to medicine, physics, etc).

* Background: HCCC
:PROPERTIES:
  :tag: HL
  :END:

** When we talk about Human-Computer Co-Creativity, what are we talking about?
We want to establish the setting in which people can understand what we’re talking about.
*** From Anna's [[https://research.aalto.fi/en/publications/five-cs-for-humancomputer-co-creativity-an-update-on-classical-cr][paper]]:
#+BEGIN_QUOTE
The new framework allows the attribution of creativity not only to individual creators but to a collective of creators, recognising the importance of meta-level communication to the creative collaboration, and the variety of creative contributions that emerge during a co-creative process. It also elaborates on the different communities and contexts surrounding co-creative collaboration and thus facilitates the analysis, evaluation and study of human–computer co-creativity by allowing researchers to describe and situate their work in the field.
#+END_QUOTE

* Background: Other
:PROPERTIES:
  :tag: HL
  :END:

** Bergson’s definition of "creativity" might be confusing for people, but it might be the the one we need to address our RQ.
https://plato.stanford.edu/entries/bergson/#CreaEvol
** Existing books about “creativity and ethics” and "technology and virtues" don’t quite cut the mustard
*** TODO Say why these aren’t sufficient answers to our questions
**** "Creativity and Ethics"
**** "Technology and the virtues: A philosophical guide to a future worth wanting"

* Survey introduction
:PROPERTIES:
  :tag: HL
  :END:

*** Assuming we have the core concepts established, the survey section should be easy to write.
Basic plan: I imagine a call ("A") and response ("B") setup. The (A)
theme is to look at what people have said in various "philosophical"
traditions — Western, nonwestern, phenomenological, experimental. The
(B) theme is to look at how these traditions have been received within
HCI and Computational Creativity research — if at all. In other words,
this is a parallel survey of two different bodies of text, drawing
connections between them. While there could be a lot of reading here,
the writing part is basically procedural.  Furthermore, we could break
down the tasks in different sub-sections to make it more focused. One
nice model for this structure of writing is [[https://mako.cc/benkler_shaw_hill-peer_production_ci.pdf][Benkler, Shaw, and Hill]]
Some methodological questions we can ask about the computing papers:
do the papers consider ethics at all? Have they sought ethics
approval?  Is ethics considered in only an immediate sense (like in a
psychology experiment) or in a broader sense (e.g., free software)? We
could also look at critical literature (e.g., dealing with AI
bias). At the end of this section, we should understand the different
extant practical approaches to ethics, and how they’re grounded in
philosophy. We can use boundary lines like “HCI” and “co-creativity”
as selection criteria to make sure that we don’t include everything.
*** [[*Main References][Main References]]
*** Based on what's raised in §1, create a taxonomic framework for the rest of the paper
This subsection should correspond to the conclusion of this section and connect all of these to subsequent *.B 
** 1.0

*** Western philosophy and ethics summary [[*1.A][1.A]]
*** How do people talk about mainstream ethics in CS? [[*1.B][1.B]]
** 1.A

*** Aristotelian vs Platonic
*** Kant and the categorical imperative
*** David Hume on the problem of induction
*** Maybe talk about the authors that break down cognitivism and agree or not - dualists, functionalists, materialists etc
*** All of this connects to philosophy of mind. Maybe necessary?
*** go deep maybe into pre-aristotle

** 1.B

Need to establish keywords from 1.A to search the literature with!
**** At this level one broadly relevant category is "law"
***** And, in particular, one sub-category is
** 2.0

*** Survey of (relevant) non-western philosophies and ethics [[*2.A][2.A]]
*** Survey of related non-western thought (e.g., *decolonial approaches* to AI) [[*2.B][2.B]]
** 2.A

*** panpsychism, buddhism, animism, ubuntu
(all universe is alive and updating materialism) - which not
necessarily might be eastern but bridge with what doesnt exist
** 2.B

What's called decolonial AI, looking at international thinking about
this — antiwestern in a way.
** 3.0

*** Phenomenology and related philosophies [[*3.A][3.A]]
*** CS/ethics related to phenomenology [[*3.B][3.B]]
** 3.A

*** husserl and heidegger all the way - what is it to be alive. 
May not be necessary to go into this - and on next chapter computational neuroscience vs all these philosophical questions might be a problem.)
*** preontology - and going to what he breaks down
*** be careful to connect this - being and everything - with ethics - Wittgenstein (ethics and aesthetics are one and the same)

** 3.B

TBA
** 4.0

It seems that philosophy has become physicalized in psychology
(Helmholtz, Kant, Freud, Jung), leading up to contemporary cognitive
science.
*** Philosophy of Cog Sci and friends [[*4.A][4.A]]
*** HCCC Ethics of Cog Sci and friends [[*4.B][4.B]]
** 4.A

*** Metacognition and ethical judgement - (maybe connect to the title here, and bring cognitive psychology to the discussion (behaviour))
*** Modelling ethics and cognition
*** Predictive Processing and Active Inference (bring embodiment to the discussion here)
*** “Ethical AI”
** 4.B

Here we look at the CS literature that incorporates an ethics related
to “Cog Sci and friends”.

*** This seems to relate to the topics discussed in [[*How AI can be a force for good][How AI can be a force for good]]
In particular, the part about “distributed agency” seems like a
cog-sci related topic.
** 5.0

Talking about human, cognitive, cultural evolution regarding all of these positions.

*** Maybe survey what is common to all of them? and how do this constraints; maybe add cultural differences and analogies;
*** Current research and breakthroughs on cognition and ethical selfawareness; metacognition and world philosophy;
*** Evolution of western thought - connections between philosophy and cognitive science.
Set up a launching pad for thinking about next steps beyond the survey.
*** Notice that now that computers are involved, the way we think about ethics and so on is likely to change.
* Case studies
:PROPERTIES:
  :tag: HL
  :END:

*** Assuming we hold on to this section, it allows us a deeper dive into some examples. Case studies would allow us to look at the concepts we've discussed in the previous sections in a real-world context. However, we’d want to be sure that these aren’t just “tacked on.” Possible examples:
**** Maybe robots?
**** [[*Mathematical creativity][Mathematical creativity]] throughout time
**** Social machines
**** [[*Logseq and friends][Logseq and friends]] — This could be a good one because it relates to the primary tool that we're using for writing this paper
** Logseq and friends

**** Logseq is part of a history of tool evolution that includes Roam Research, which has been massively capitalized recently
**** Other relevant tools in the same space include Org Roam (that one is open source)
**** Logseq itself is open source
**** The software is linked with a pseudo-ethical method: zettelkasten
***** https://en.wikipedia.org/wiki/Zettelkasten
**** I previously worked on a paper in this space: Massively distributed authorship of academic papers
Tomlinson, B., Ross, J., André, P., et al. 2012. Massively distributed authorship of academic papers. CHI’12 Extended Abstracts on Human Factors in Computing Systems, ACM, 11–20.



** How AI can be a force for good

*** Distributed agency
#+BEGIN_QUOTE
With distributed agency comes distributed responsibility. Existing ethical frameworks address individual, human responsibility, with the goal of allocating punishment or reward based on the actions and intentions of an individual. They were not developed to deal with distributed
responsibility.
#+END_QUOTE
**** https://drive.google.com/drive/u/1/folders/13bwMQfn8RY67-znVdnC7WO6OdcpDtR83
**** This seems like an important point: we'll need new (not necessarily "agential") ways to think about ethics.
**** It seems useful to apply this in somewhat more general terms about "intelligent systems" — or just "systems with emergent properties"; so, if distributed agents produce e.g., environmental degradation, that's not ethical, and the system as a whole "should" find ways to improve its behaviour.  This sort of thing is thought about in Elinor Ostrom's economics.
**** A particular concern of Taddeo & Floridi here seems to be "autonomy" of AI, and "self-determination" of humans. But in the case of HCI/HCCC it's not totally clear that either of these criteria apply.  In HCCC it's much closer to anthropotechnics
***** https://www.wired.com/beyond-the-beyond/2015/09/peter-sloterdijk-anthropotechnics/

*** Regulation
#+BEGIN_QUOTE
Humanity learned this lesson the hard way when it did not regulate the impact of the industrial revolution on labor forces, and also when it recognized too late the environmental impact of massive industrialization and global consumerism.
#+END_QUOTE
**** I think it's worthwhile to think of these things as *not separate* from AI issues
***** Supplementary info:
https://science.sciencemag.org/content/suppl/2018/08/22/361.6404.751.DC1
** Mathematical creativity

*** Section introduction: Objectives
Have we built up enough of a repertoire to do a deep dive on mathematical creativity?
*** What is mathematics? martin heidegger anything learnable as such. Jorge Luís Borges - the map argument;
*** The end of cognition and human ability? The limits of reality and the limits of math (e.g. dimensionality)
*** Mathematical creativity as an example - and so what in what ways does it actually ramifies

* Discussion
:PROPERTIES:
  :tag: HL
  :END:

*** The Discussion is a bit hard to chart in advance, but roughly it asks: having done this survey, and looked at a couple case studies, have we learned anything that's relevant for practice? Maybe here is a good time to return to some of the debates that look at "creativity" in a more mainstream sense, e.g., Anna Kantosalo and Ben Schneiderman about creative systems and social inclusion vs exclusion? From the point of view of "Methods", hopefully we will have clarified at the start why we think this sort of activity could lead to new insights! Now, at the end, we might draw some conclusions about how "HCI" allows us to do global research, build projects involving people from around the world, with rich access to the world’s knowledge resources. We might also have something to say about why Ethical AI is so trendy right now, and perhaps even speculate a bit about its future!
*** Some possible places this could go:
**** How can I practically engage with these issues as a computer science researcher?
**** Tech design and CS thinking: creativity as mirror of ethical principles
**** Research Ethics
**** Interfaces and establishing relationships between people and things?
**** How do I relate to knowledge, and with/to the whole body of historical philosophy, science, inquiry, and maybe AI and tech systems?
** mind

**** What does mind mean?
**** What is mind
** Premises

*** We’ve entered into a new era, and we need to understand what’s going on.
*** Although part of this is the legacy of the industrial revolution, computers have played a significant role in the growth of knowledge
*** In a certain sense the CS field is playing “catch-up” with CMC: we invent new paradigms for interaction (e.g., Wikipedia, machine learning)
*** However, we don’t yet have a robust way to /think/ about human computer interaction at this broad scale
*** We try to wrap our minds around “Human-Computer Co-Creativity” by looking at CMC, HCI, and CI.
Let’s work our way up to discussing HCCC by starting with “human
co-creativity using computers”, and introduce AI once we have a grasp
of how computer mediated communication and collective intelligence
works.


** Scope

*** TOCHI’s statement of purpose

#+begin_quote
ACM Transactions on Computer-Human Interaction (TOCHI) covers the
software, hardware and human aspects of interaction with
computers. Topics include hardware and software architectures;
interactive techniques, metaphors, and evaluation; user interface
design processes; and users and groups of users. Those within the
artificial intelligence, object-oriented systems, information systems,
graphics and software engineering communities, will benefit from the
high quality research papers in TOCHI concerning information and ideas
directly related to the construction of effective human-computer
interfaces.
#+end_quote

*** Our research question within this area:
**** Is there an ethical use of computer technology, and if so, what is it?  How would we get intuitions about that?
**** What is our orientation towards computers broadly put?
**** How can we bring a deeper foundation for the ethical use of intelligence technology?
** Main References

*** "Who else has attempted anything similar or related to this in the past?"
*** This is not to say that these are necessarily "our" main references
*** [[https://en.wikipedia.org/wiki/Bernard_Stiegler#Books_in_English][Bernard Stiegler]] — philosophy of technics and other works
*** [[https://en.wikipedia.org/wiki/Peter_Sloterdijk#Works_in_English_translation][Peter Sloterdijk]] — philosophy of the human environment
*** James Lovelock — /Novacene: The coming age of hyperintelligence/ — This is good because of the evolutionary perspective, though his reasoning may be a bit off
