#+title: 1.A

* Aristotelian vs Platonic
* Kant and the categorical imperative
* David Hume on the problem of induction
* Maybe talk about the authors that break down cognitivism and agree or not - dualists, functionalists, materialists etc
* All of this connects to philosophy of mind. Maybe necessary?
* go deep maybe into pre-aristotle
* Further notes here:
- **1)** *(1785) Kant (Johnson and Cureton 2004) proposed that the fundamental principle of our moral duties is a categorical imperative.*
- **2)** *(2018) (Noa Naaman-Zauderer) both Descartes and Spinoza thinkers define virtue in terms of activity or freedom, mutatis mutandis, and thus in terms of actual power of acting. Second, I will claim that both Descartes and Spinoza hold a non-consequentialist approach to virtue, by which human actions are evaluated as virtuous or good on the basis of their motivational forces rather than their consequences.*
- **3** *(2004) (stanford encyclopedia) More specifically then, Bergson’s project in Creative Evolution is to offer a philosophy capable of accounting both for the continuity of all living beings—as creatures—and for the discontinuity implied in the evolutionary quality of this creation.*
- **4** *(2004) (stanford encyclopedia) Hans Vaihinger - Die Philosophie des Als Ob : Vaihinger comes to view Kant’s doctrine of the essential limits of our cognition through this Schopenhauerian-Darwinian lens: the “limitations of human knowledge,” he says, are “a necessary and natural result of the fact that thought and knowledge are originally only a means, to attain the Life-purpose, so that their actual independence signifies a breaking-away from their original purpose; indeed, by the fact of this breaking-loose, thought is confronted by impossible problems” (PAO xviii). Vaihinger will use this idea to motivate his own fictionalism, and to provide a radical reinterpretation of Kantianism.*
- [https://plato.stanford.edu/entries/ethics-ancient/ ](/xZCXvatGRw2CA5FwoBjYIQ)
