#+title: 1.A

# This is a temporary comment until I write C-x C-s
# or until it autosaves a backup.
* Our definition
Human beings have always been interested in categorizing their
behaviour. Classification and criticism, personal and interpersonal,
about actions taken towards the world. When this criticism is made,
there is no way that it will not be realized subjectively (lens
argument), even if it embraces generalization. This recursive feedback
to outselves has allowed the analysis and assessment of actions that
we deem meaningful - or that others consider significant in us -
originating fundamental positions for human understanding from the
human. It is not in vain that *ethics* derives from the Greek "ēthikós"
(ἠθικός) that means "relating to one's character" - as a relational
loop. Indeed, a deeper etymology points to both habit and environment;
ἤθεα meaning “accustomed place” (as in ἤθεα ἵππων “the habitat of
horses”, Iliad, 6.51115.265).  This points to an "ethological" side of
"ethics", which is pursued, e.g., by Spinoza (as per Deleuze's
reading). Importantly, our environments include *others* and provide
grounds for interaction. Just as I consider myself, I can imagine the
way others consider me, consider them, and develop collaborative
processes for all this. Right here comes ethics and the way it will
happen in society. Paul and Elder (2003) define *ethics* as: “a
nondetermined set of concepts, principles and metarules that guide us
in determining what behavior (acting towards) helps and/or harms
sentient creatures.”  Taking this as our "working definition" allows
us to develop ethics helps to create a relationship structure.
** [[Ethics and Ethology in Homer]]
* Aristotelian vs Platonic
* Kant and the categorical imperative
* David Hume on the problem of induction
* Maybe talk about the authors that break down cognitivism and agree or not - dualists, functionalists, materialists etc
* All of this connects to philosophy of mind. Maybe necessary?
* go deep maybe into pre-aristotle
* Further notes here:
-  *(1785) Kant (Johnson and Cureton 2004) proposed that the fundamental principle of our moral duties is a categorical imperative.*
- (2018) (Noa Naaman-Zauderer) both Descartes and Spinoza thinkers define virtue in terms of activity or freedom, mutatis mutandis, and thus in terms of actual power of acting. Second, I will claim that both Descartes and Spinoza hold a non-consequentialist approach to virtue, by which human actions are evaluated as virtuous or good on the basis of their motivational forces rather than their consequences.*
- (2004) (stanford encyclopedia) More specifically then, Bergson’s project in Creative Evolution is to offer a philosophy capable of accounting both for the continuity of all living beings—as creatures—and for the discontinuity implied in the evolutionary quality of this creation.*
- (2004) (stanford encyclopedia) Hans Vaihinger - Die Philosophie des Als Ob : Vaihinger comes to view Kant’s doctrine of the essential limits of our cognition through this Schopenhauerian-Darwinian lens: the “limitations of human knowledge,” he says, are “a necessary and natural result of the fact that thought and knowledge are originally only a means, to attain the Life-purpose, so that their actual independence signifies a breaking-away from their original purpose; indeed, by the fact of this breaking-loose, thought is confronted by impossible problems” (PAO xviii). Vaihinger will use this idea to motivate his own fictionalism, and to provide a radical reinterpretation of Kantianism.*
- [https://plato.stanford.edu/entries/ethics-ancient/ ](/xZCXvatGRw2CA5FwoBjYIQ)
* [[Holistic views of philosophy]]
