#+TITLE: Case studies
#+roam_tags: HL

** Assuming we hold on to this section, it allows us a deeper dive into some examples. Case studies would allow us to look at the concepts we've discussed in the previous sections in a real-world context. However, we’d want to be sure that these aren’t just “tacked on.” Possible examples:
*** Maybe robots?
*** [[file:mathematical_creativity.org][Mathematical creativity]] throughout time
*** Social machines
*** [[file:logseq_and_friends.org][Logseq and friends]] — This could be a good one because it relates to the primary tool that we're using for writing this paper
** Historical setting: computers have played a significant and increasing role since their introduction.  Whereas there are mature paradigms for interaction *using* computers (e.g., Wikipedia), the paradigms of interacting *with* computers (e.g., Cambridge Analytica) continue to raise problematic issues.  At the same time, there are many unsolved problems that humans together with computers are working to address (e.g., climate change)!
** [[Case studies reprise]]
