#+TITLE: Data Epistemologies, The Coloniality of Power, and Resistance

** This will be one of the major topics of the Peeragogy podcast episode on January 13, 2020
** I've known the author, Paola Ricaurte, for years, but haven't yet engaged much with her research!
** The other interviewee is Yasmine Boudiaf, who I met in 2020
**
#+BEGIN_QUOTE
This epistemology, which represents a more complex evolution of the post-positivist paradigm, is based on three assumptions: (1) data reflects reality, (2) data analysis generates the most valuable and accurate knowledge, and (3) the results of data processing can be used to make better decisions about the world. Nevertheless, all these assumptions should be contested and analyzed in a
broader framework that considers how this form of knowledge production increases capital concentration (West 2017), surveillance (Zuboff 2015), and colonization (Couldry and Mejias 2019).
#+END_QUOTE
** The themes remind be of the book "Columbus and other Cannibals" by Jack D Forbes that I read recently
**
#+BEGIN_QUOTE
How do the underlying power relations affect populations that exist outside this knowledge order?
#+END_QUOTE
** The issues seem relevant also inside of places like the US (we shouldn't forget that colonialism exists there!)
**
#+BEGIN_QUOTE
One proposal to bring balance to the data extractivism model suggests compensating individuals for their contribution to the digital economy and supporting competitive markets
#+END_QUOTE
** Paola rejects that idea as too linked to capitalism and markets. Instead:
**
#+BEGIN_QUOTE
Decolonial thinking and epistemic disobedience demand the transformation of the structure of power by taking “control over labor/resources/product, over sex/resources/products, over authorities/institutions/violence, and over intersubjectivity/knowledge/communication to the daily life of the people” (Quijano 2000, 573).
#+END_QUOTE
** "Peeragogy" seems relevant to this issue of taking (back) control.
** "Data Assemblages" c/o Kitchin
** Table 1 is a very useful summary of the harms & inequities associated with the current default model.  I wonder how they relate to the kind of thinking in R. M. Unger's agitation for a "[[Knowledge Economy]]"
**
#+BEGIN_QUOTE
data resistance practices
#+END_QUOTE
** I wonder what these are
**
#+BEGIN_QUOTE
(1) developing legal frameworks (2) designing public policy, (3) using artificial intelligence systems for public administration, (4) hiring technological services, (5) acquiring products for public administration and surveillance purposes, (6) implementing public policies and digital agendas, and (7) facilitating education and the development of labor forces.
#+END_QUOTE
**
#+BEGIN_QUOTE
In many cases, indigenous populations are being recolonized through datafication and public policies regarding the implementation of digital literacy programs or digital citizenship policies.
#+END_QUOTE
**
#+BEGIN_QUOTE
Several citizen projects address this official data gap through maps and visualizations.
#+END_QUOTE
** The theme of missing data on how many people are killed isn't expanded in detail in this paper, so the reference needs to be chased.
