#+TITLE: Discussion
#+roam_tags: HL

** The Discussion is a bit hard to chart in advance, but roughly it asks: having done this survey, and looked at a couple case studies, have we learned anything that's relevant for practice? Maybe here is a good time to return to some of the debates that look at "creativity" in a more mainstream sense, e.g., Anna Kantosalo and Ben Schneiderman about creative systems and social inclusion vs exclusion? From the point of view of "Methods", hopefully we will have clarified at the start why we think this sort of activity could lead to new insights! Now, at the end, we might draw some conclusions about how "HCI" allows us to do global research, build projects involving people from around the world, with rich access to the world’s knowledge resources. We might also have something to say about why Ethical AI is so trendy right now, and perhaps even speculate a bit about its future!
** Some possible places this could go:
*** How can I practically engage with these issues as a computer science researcher?
*** Tech design and CS thinking: creativity as mirror of ethical principles
*** Research Ethics
*** Interfaces and establishing relationships between people and things?
*** How do I relate to knowledge, and with/to the whole body of historical philosophy, science, inquiry, and maybe AI and tech systems?
