#+TITLE: Holistic views of philosophy

** - E.g., Japanese robots as a reflection on Shinto religion
- ‘Ubuntu’ is the name of a popular GNU/Linux distribution. Maybe compare with the story of **Wakanda** in "Black Panther"; the things that made humanity work in the past are the core 'technology' we have now.  Our brains haven't changed in 10000 years, whereas technology has changed a lot (and here we could reference different models of technology building on previous technology, more in the evolutionary section).  The way we "do" our ethics is not just embodied in language, but also in technologies.  This influences the way we *talk about technologies*. Taking the future in mind, things may or may not work as imagined. If they were writing in 1950s they wouldn't have imagined things the same way. To write this paper we have to be futurists!  If we look at, e.g., the Chinese government, but we have people building the Matrix, with lot of funding. We can't be afraid of saying "There will be AIs more smarter than humans". We have to criticise e.g. functional intelligence vs creativity; we need to find ways to talk about the future.
- We want something a bit like the US constitution, or perhaps the Icelandic constitution. "How will it be in 20 years?"
- Building something that e.g. labour organisers & ML programmers can meet in the middle (and other stakeholders as well)
- Luis is working with an artist who is interested in neuroscience and art and memory... she goes really to the simulation stuff... Cf. **Westworld** as an example as where the actor is dressing & there is a robot... she says "You want to ask...?" — "Are you real...?" — if you can't tell, does it matter?  The way I see myself matters. Human dignity vs perception?
- We still see Turing, even if the GPU is going on now, even if we crack the Turing Test... (cf. earlier science fiction precursors)
- - This is a space where we make the same thing we did in the past? "Uncanny Valley"... You get an observer paradox b/c you can't actually revisit the same thing twice, by the time you observe it again it has changed.
- "Patternist" philosophy, related to panpsychism, Hofstadter - e.g. grandmother neurons — this is not so holistic as some of the opinions we had. You can quickly lose yourself in panpsychism, though. The word "consciousness" — what comes when you wake up and goes away when you go to sleep.. — this represents something that has degrees and types across the whole universe. You can then start to ask questions like, why does this type of consciousness that happens in this types of system... is much more more *interesting* than what happens in a rock. This may not function with a more functionalist perspective (which don't claim to represent the whole universe).
** []
