#+TITLE: How do we use ethics

** how do I apply ethics in systems - building/using/rebuilding/thinking

- how do systems apply ethics in themselves 
- E.g. (Illustration) "Guns, Germs, and Steel" — can this be used to change the world? — This is why this relates to arts & to the ontologically subjective.
  - Guns don't evolve; germs do... but not 'intelligently'.
  - 'Mindset view'; you can view things as organizations or as people?
  - "Ultra Society" — Peter Turchin, societal change, physical violence to the body — but changes can actually predate the violence
  - "Killing of people & being replaced by new ideas"
  - JC: Take a look at the Minnesota tech change econ stuff
- 'Science is making a map of the world'... because of the nature of your reality (you can't validate Marx...) You can understand what he meant, try to apply it to yourself, see how it applies, maybe this can make you a better person. It's not law!  You are your own 'sponge' of the world!
  - Reading text can be as bad for your body as physical violence
