#+title: Introduction
#+roam_tags: HL

* The Introduction will have to do some heavy lifting to explain that we're talking about "creativity" in a way that's not entirely familiar. I want to re-imagine "Human Computer Interaction" as a co-evolutionary process that has been developing over long time spans. There's nothing too shocking about that, but it can be hard to express in words. To make the paper accessible to reviewers we need to be careful how we present our concepts of "creativity" and "ethics". The basic motivation is that ethics is pretty hard for humans to get right (e.g., consider climate change, genocides, etc.), so we need to think about computational ethics not just in terms of trolley problems, but in a broader context. Similarly, we want to look at “creativity” not just in terms of an auteur — or even necessarily a single agent!
* [[file:./premises.org][Premises]] — /‘Human-computer interaction’ is a bigger deal than we might think at first glance!.../
* [[file:./scope.org][Scope]]— TOCHI — /covers humans interacting with computers/
:PROPERTIES:
:later: 1607173640608
:done: 1607173639362
:END:
** Our RQ: WHAT ARE SUITABLE ETHICS FOR HCI+HCCC DESIGNERS?
* [[file:./approach.org][Approach]] — /We will survey philosophy and its applications in CS; then, we will describe possible next steps for research./
* [[file:treatment.org][Treatment]] — Add the longer narrative introduction from HackMD (5 Feb 2021)
