#+TITLE: Machines Who Think: A Personal Inquiry into the History and Prospects of Artificial Intelligence

** This is a book about AI. It relates to the [[Case studies]], insofar as it came up in a footnote in Stephanie Dick's "AfterMath"
** S. Dick's paper talks about the role of hybrid systems, which has come up again in Chess and will likely be prevalent in other fields:
** 
#+BEGIN_QUOTE
the character and capacities of computer work and human work depend on the nature of human–computer interactions and their mutual enabling and/or inhibiting in specific systems.
#+END_QUOTE
** She talks about a "cultural materialism" in science.
#+BEGIN_QUOTE
As will be discussed at length in the next section, one way that intuition was imparted to the computer program was as a weighting mechanism for privileging certain inference paths over others
#+END_QUOTE
** 
#+BEGIN_QUOTE
AURA was not merely a receptacle of prenegotiated social practices but, rather, surprised and resisted its users, participating in the negotiations that precipitated a change in mathematical thinking and problem solving. I hope that historians of mathematics will continue to investigate more instances of such negotiation.
#+END_QUOTE
**
