#+TITLE: Machines Who Think: A Personal Inquiry into the History and Prospects of Artificial Intelligence

** This is a book about AI. It relates to the [[Case studies]], insofar as it came up in a footnote in Stephanie Dick's "AfterMath"
** S. Dick's paper talks about the role of hybrid systems, which has come up again in Chess and will likely be prevalent in other fields:
** 
#+BEGIN_QUOTE
the character and capacities of computer work and human work depend on the nature of human–computer interactions and their mutual enabling and/or inhibiting in specific systems.
#+END_QUOTE
** She talks about a "cultural materialism" in science.
#+BEGIN_QUOTE
As will be discussed at length in the next section, one way that intuition was imparted to the computer program was as a weighting mechanism for privileging certain inference paths over others
#+END_QUOTE
** This reminds me of my preprint about serendipity.
#+BEGIN_QUOTE
The capacity to identify what was “promising” or “interesting” was precisely one of those unautomatable human abilities, since, without guidance, computers indiscriminately produce all consequences.
#+END_QUOTE
**
