#+TITLE: Phenomenology and being

** - Husserl
- **Heidegger** (I think we need to criticize Kant and the rational here) — also critiquing/revisiting things like *mathematics* as the study of things that are learnable as such. Why was Heidegger writing in 21st Century? Also about technology; but this is really about Dasein. Japanese and Germans caring about their children. It's an ontological crisis. And it's completely different from Descrates who said "Only humans can be rational". At that point, what Descrartes made some sense. (Cf. Fineas Gauge, who became different in a way that was unexpected.) 
- Mark, Heidegger, talking about the **ready-at-hand**, the part of the hammer that you're familiar with... your awareness of the fundamental thing you were using
- What is it to be alive?
- preontology
- be careful to connect this - being and everything - with ethics - Wittgenstein (ethics and aesthetics are one and the same)
- With Foucault and others, you can see the internet coming; Visionaries are still stuck with imagining things in terms of the contents and contexts of their historical time.
